/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A list of loot entries for InControl mod
 */
export type InControlLoot = {
  item?: string | string[];
  itemcount?: string;
  nbt?: {
    [k: string]: unknown;
  };
  remove?: string | string[];
  removeall?: boolean;
  baby?: boolean;
  biome?: string | string[];
  biometags?: string | string[];
  biometype?: string | string[];
  block?:
    | string
    | string[]
    | {
        [k: string]: unknown;
      };
  blockoffset?: {
    [k: string]: unknown;
  };
  bothhandsitem?:
    | string
    | string[]
    | {
        [k: string]: unknown;
      };
  category?: string | string[];
  difficulty?: "easy" | "normal" | "hard" | "peaceful";
  dimension?: string | string[];
  dimensionmod?: string | string[];
  explosion?: boolean;
  fakeplayer?: boolean;
  fire?: boolean;
  gamestage?: string;
  hostile?: boolean;
  inbuilding?: boolean;
  incity?: boolean;
  insphere?: boolean;
  instreet?: boolean;
  magic?: boolean;
  maxdifficulty?: number;
  maxheight?: number;
  maxlight?: number;
  maxspawndist?: number;
  maxtime?: number;
  mindifficulty?: number;
  minheight?: number;
  minlight?: number;
  minspawndist?: number;
  mintime?: number;
  mob?: string | string[];
  mod?: string | string[];
  offhanditem?:
    | string
    | string[]
    | {
        [k: string]: unknown;
      };
  passive?: boolean;
  player?: boolean;
  playerhelditem?:
    | string
    | string[]
    | {
        [k: string]: unknown;
      };
  projectile?: boolean;
  random?: number;
  realplayer?: boolean;
  seesky?: boolean;
  source?: string | string[];
  structure?: string;
  weather?: "rain" | "thunder";
}[];
