/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A list of spawner entries for InControl mod
 */
export type InControlSpawner = {
  mob?: string | string[];
  phase?: string | string[];
  mobsfrombiome?:
    | "monster"
    | "creature"
    | "ambient"
    | "water_creature"
    | "water_ambient"
    | "misc";
  attempts?: number;
  persecond?: number;
  amount?: {
    minimum: number;
    maximum: number;
    groupdistance?: number;
  };
  conditions: {
    dimension: string | string[];
    mindaycount?: number;
    maxdaycount?: number;
    mindist?: number;
    maxdist?: number;
    minheight?: number;
    maxheight?: number;
    norestrictions?: boolean;
    inliquid?: boolean;
    inwater?: boolean;
    inlava?: boolean;
    inair?: boolean;
    maxthis?: number;
    maxtotal?: number;
    maxpeaceful?: number;
    maxhostile?: number;
    maxneutral?: number;
    maxlocal?: number;
  };
}[];
