/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Hostile Neural Networks data model datapack file
 */
export interface HostileNeuralNetworksDataModel {
  entity: string;
  conditions?: unknown[];
  variants?: unknown[];
  name?: string;
  name_color?: string;
  gui_scale?: number;
  gui_x_offset?: number;
  gui_y_offset?: number;
  gui_z_offset?: number;
  sim_cost?: number;
  display_nbt?: {
    [k: string]: unknown;
  };
  input?: Item;
  base_drop?: Item;
  trivia?: string;
  fabricator_drops?: {
    item: string;
    count?: number;
    optional?: boolean;
    [k: string]: unknown;
  }[];
  tier_data?: number[];
  data_per_kill?: number[];
}
export interface Item {
  item: string;
  count?: number;
  [k: string]: unknown;
}
