REIEvents.groupEntries((event) => {
  // This cannot be initialized outside of the event due to REI being weird and relying on class loading order.
  const $VanillaEntryTypes = Java.loadClass(
    "me.shedaniel.rei.api.common.entry.type.VanillaEntryTypes",
  );

  event.groupItems("kubejs:rei_groups/templates", "Templates", [
    "sf5_things:treasure_bag_template",
    "silentgear:rod_template",
    "silentgear:tip_template",
    "silentgear:coating_template",
    "silentgear:grip_template",
    "silentgear:binding_template",
    "silentgear:lining_template",
    "silentgear:cord_template",
    "silentgear:fletching_template",
    "silentgear:sword_template",
    "silentgear:katana_template",
    "silentgear:machete_template",
    "silentgear:spear_template",
    "silentgear:trident_template",
    "silentgear:knife_template",
    "silentgear:dagger_template",
    "silentgear:pickaxe_template",
    "silentgear:shovel_template",
    "silentgear:axe_template",
    "silentgear:paxel_template",
    "silentgear:hammer_template",
    "silentgear:excavator_template",
    "silentgear:saw_template",
    "silentgear:hoe_template",
    "silentgear:mattock_template",
    "silentgear:prospector_hammer_template",
    "silentgear:sickle_template",
    "silentgear:shears_template",
    "silentgear:fishing_rod_template",
    "silentgear:bow_template",
    "silentgear:crossbow_template",
    "silentgear:slingshot_template",
    "silentgear:shield_template",
    "silentgear:helmet_template",
    "silentgear:chestplate_template",
    "silentgear:leggings_template",
    "silentgear:boots_template",
    "silentgear:elytra_template",
    "silentgear:arrow_template",
    "silentgear:ring_template",
    "silentgear:bracelet_template",
    "silentgear:template_board",
  ]);

  // Creative items
  event.groupItems("kubejs:rei_groups/creative_items", "Creative Items", [
    "ae2:creative_energy_cell",
    "ae2:creative_item_cell",
    "ae2:creative_fluid_cell",
    "wormhole:creative_energy_cell",
    "cyclic:battery_infinite",
    "spelled:creative_tome",
    "create:creative_motor",
    "create:creative_fluid_tank",
    "create:creative_crate",
    "create:creative_blaze_cake",
    "create:handheld_worldshaper",
    "botania:creative_pool",
    "botania:infrangible_platform",
    "botania:lens_storm",
    "botania:mana_tablet",
    "botania:corporea_spark_creative",
    "littlelogistics:creative_capacitor",
    "thermal:rf_coil_creative_augment",
    "thermal:fluid_tank_creative_augment",
    "thermal:machine_efficiency_creative_augment",
    "thermal:machine_catalyst_creative_augment",
    "immersiveengineering:capacitor_creative",
    "ars_nouveau:creative_spell_book",
    "ars_nouveau:creative_source_jar",
    "mininggadgets:upgrade_battery_creative",
    "draconicevolution:creative_capacitor",
    "draconicevolution:creative_op_capacitor",
    "rftoolsutility:creative_screen",
    "enderio:creative_power",
    "createaddition:creative_energy",
  ]);

  // Coral
  event.groupItems("kubejs:rei_groups/coral", "Coral", [
    "minecraft:dead_tube_coral_block",
    "minecraft:dead_brain_coral_block",
    "minecraft:dead_bubble_coral_block",
    "minecraft:dead_fire_coral_block",
    "minecraft:dead_horn_coral_block",
    "minecraft:tube_coral_block",
    "minecraft:brain_coral_block",
    "minecraft:bubble_coral_block",
    "minecraft:fire_coral_block",
    "minecraft:horn_coral_block",
    "minecraft:tube_coral",
    "minecraft:brain_coral",
    "minecraft:bubble_coral",
    "minecraft:fire_coral",
    "minecraft:horn_coral",
    "minecraft:dead_brain_coral",
    "minecraft:dead_bubble_coral",
    "minecraft:dead_fire_coral",
    "minecraft:dead_horn_coral",
    "minecraft:dead_tube_coral",
    "minecraft:tube_coral_fan",
    "minecraft:brain_coral_fan",
    "minecraft:bubble_coral_fan",
    "minecraft:fire_coral_fan",
    "minecraft:horn_coral_fan",
    "minecraft:dead_tube_coral_fan",
    "minecraft:dead_brain_coral_fan",
    "minecraft:dead_bubble_coral_fan",
    "minecraft:dead_fire_coral_fan",
    "minecraft:dead_horn_coral_fan",
    "exnihilosequentia:fire_coral_larva",
    "exnihilosequentia:tube_coral_larva",
    "exnihilosequentia:brain_coral_larva",
    "exnihilosequentia:bubble_coral_larva",
    "exnihilosequentia:horn_coral_larva",
  ]);

  // Pottery Sherds
  event.groupItems("kubejs:rei_groups/pottery_sherds", "Pottery Sherds", [
    "minecraft:angler_pottery_sherd",
    "minecraft:archer_pottery_sherd",
    "minecraft:arms_up_pottery_sherd",
    "minecraft:blade_pottery_sherd",
    "minecraft:brewer_pottery_sherd",
    "minecraft:burn_pottery_sherd",
    "minecraft:danger_pottery_sherd",
    "minecraft:explorer_pottery_sherd",
    "minecraft:friend_pottery_sherd",
    "minecraft:heart_pottery_sherd",
    "minecraft:heartbreak_pottery_sherd",
    "minecraft:howl_pottery_sherd",
    "minecraft:miner_pottery_sherd",
    "minecraft:mourner_pottery_sherd",
    "minecraft:plenty_pottery_sherd",
    "minecraft:prize_pottery_sherd",
    "minecraft:sheaf_pottery_sherd",
    "minecraft:shelter_pottery_sherd",
    "minecraft:skull_pottery_sherd",
    "minecraft:snort_pottery_sherd",
  ]);

  // RFTools Dimlets
  event.groupItems("kubejs:rei_groups/rftools_dimlets", "RFTools Dimlets", [
    "rftoolsdim:empty_terrain_dimlet",
    "rftoolsdim:empty_dimlet",
    "rftoolsdim:empty_attribute_dimlet",
    "rftoolsdim:empty_feature_dimlet",
    "rftoolsdim:empty_structure_dimlet",
    "rftoolsdim:empty_biome_dimlet",
    "rftoolsdim:empty_biome_controller_dimlet",
    "rftoolsdim:empty_biome_category_dimlet",
    "rftoolsdim:empty_block_dimlet",
    "rftoolsdim:empty_fluid_dimlet",
    "rftoolsdim:empty_time_dimlet",
    "rftoolsdim:empty_tag_dimlet",
    "rftoolsdim:empty_sky_dimlet",
    "rftoolsdim:terrain_dimlet",
    "rftoolsdim:attribute_dimlet",
    "rftoolsdim:feature_dimlet",
    "rftoolsdim:structure_dimlet",
    "rftoolsdim:biome_dimlet",
    "rftoolsdim:biome_controller_dimlet",
    "rftoolsdim:biome_category_dimlet",
    "rftoolsdim:block_dimlet",
    "rftoolsdim:fluid_dimlet",
    "rftoolsdim:time_dimlet",
    "rftoolsdim:tag_dimlet",
    "rftoolsdim:sky_dimlet",
  ]);

  // Armor Items
  event.groupItems("kubejs:rei_groups/armor", "Armor", [
    "minecraft:turtle_helmet",
    "minecraft:leather_helmet",
    "minecraft:leather_chestplate",
    "minecraft:leather_leggings",
    "minecraft:leather_boots",
    "minecraft:chainmail_helmet",
    "minecraft:chainmail_chestplate",
    "minecraft:chainmail_leggings",
    "minecraft:chainmail_boots",
    "minecraft:iron_helmet",
    "minecraft:iron_chestplate",
    "minecraft:iron_leggings",
    "minecraft:iron_boots",
    "minecraft:diamond_helmet",
    "minecraft:diamond_chestplate",
    "minecraft:diamond_leggings",
    "minecraft:diamond_boots",
    "minecraft:golden_helmet",
    "minecraft:golden_chestplate",
    "minecraft:golden_leggings",
    "minecraft:golden_boots",
    "minecraft:netherite_helmet",
    "minecraft:netherite_chestplate",
    "minecraft:netherite_leggings",
    "minecraft:netherite_boots",
    "forcecraft:force_helmet",
    "forcecraft:force_chest",
    "forcecraft:force_legs",
    "forcecraft:force_boots",
    "botania:manasteel_helmet",
    "botania:manasteel_chestplate",
    "botania:manasteel_leggings",
    "botania:manasteel_boots",
    "botania:elementium_helmet",
    "botania:elementium_chestplate",
    "botania:elementium_leggings",
    "botania:elementium_boots",
    "botania:terrasteel_helmet",
    "botania:terrasteel_chestplate",
    "botania:terrasteel_leggings",
    "botania:terrasteel_boots",
    "botania:manaweave_helmet",
    "botania:manaweave_chestplate",
    "botania:manaweave_leggings",
    "botania:manaweave_boots",
    "botania:ancient_will_verac",
    "overweight_farming:straw_hat",
    "thermal:beekeeper_helmet",
    "thermal:beekeeper_chestplate",
    "thermal:beekeeper_leggings",
    "thermal:beekeeper_boots",
    "thermal:diving_helmet",
    "thermal:diving_chestplate",
    "thermal:diving_leggings",
    "thermal:diving_boots",
    "thermal:hazmat_helmet",
    "thermal:hazmat_chestplate",
    "thermal:hazmat_leggings",
    "thermal:hazmat_boots",
    "immersiveengineering:armor_steel_helmet",
    "immersiveengineering:armor_steel_chestplate",
    "immersiveengineering:armor_steel_leggings",
    "immersiveengineering:armor_steel_boots",
    "immersiveengineering:armor_faraday_helmet",
    "immersiveengineering:armor_faraday_chestplate",
    "immersiveengineering:armor_faraday_leggings",
    "immersiveengineering:armor_faraday_boots",
    "pizzacraft:chef_hat",
    "pizzacraft:chef_shirt",
    "pizzacraft:chef_leggings",
    "pizzacraft:chef_boots",
    "pizzacraft:pizza_delivery_cap",
    "pizzacraft:pizza_delivery_shirt",
    "pizzacraft:pizza_delivery_leggings",
    "pizzacraft:pizza_delivery_boots",
    "ars_nouveau:sorcerer_boots",
    "ars_nouveau:sorcerer_leggings",
    "ars_nouveau:sorcerer_robes",
    "ars_nouveau:sorcerer_hood",
    "ars_nouveau:arcanist_boots",
    "ars_nouveau:arcanist_robes",
    "ars_nouveau:arcanist_hood",
    "ars_nouveau:battlemage_boots",
    "ars_nouveau:battlemage_leggings",
    "ars_nouveau:battlemage_robes",
    "ars_nouveau:battlemage_hood",
    "mob_grinding_utils:monocle",
    "vinery:straw_hat",
    "vinery:winemaker_apron",
    "vinery:winemaker_leggings",
    "vinery:winemaker_boots",
    "create:copper_diving_helmet",
    "create:netherite_diving_helmet",
    "create:copper_diving_boots",
    "vinery:bottle_mojang_noir",
    "create:netherite_diving_boots",
    "monsterplus:crystal_helmet",
    "monsterplus:crystal_chestplate",
    "monsterplus:crystal_leggings",
    "monsterplus:crystal_boots",
    "friendsandfoes:wildfire_crown",
    "mysticalagriculture:inferium_helmet",
    "mysticalagriculture:inferium_chestplate",
    "mysticalagriculture:inferium_leggings",
    "mysticalagriculture:inferium_boots",
    "mysticalagriculture:prudentium_helmet",
    "mysticalagriculture:prudentium_chestplate",
    "mysticalagriculture:prudentium_leggings",
    "mysticalagriculture:prudentium_boots",
    "mysticalagriculture:tertium_helmet",
    "mysticalagriculture:tertium_chestplate",
    "mysticalagriculture:tertium_leggings",
    "mysticalagriculture:tertium_boots",
    "mysticalagriculture:imperium_helmet",
    "mysticalagriculture:imperium_chestplate",
    "mysticalagriculture:imperium_leggings",
    "mysticalagriculture:imperium_boots",
    "mysticalagriculture:supremium_helmet",
    "mysticalagriculture:supremium_chestplate",
    "mysticalagriculture:supremium_leggings",
    "mysticalagriculture:supremium_boots",
    "mysticalagriculture:awakened_supremium_helmet",
    "mysticalagriculture:awakened_supremium_chestplate",
    "mysticalagriculture:awakened_supremium_leggings",
    "mysticalagriculture:awakened_supremium_boots",
  ]);

  // Tools
  event.groupItems("kubejs:rei_groups/tools", "Tools", [
    "minecraft:wooden_sword",
    "minecraft:wooden_shovel",
    "minecraft:wooden_pickaxe",
    "minecraft:wooden_axe",
    "minecraft:wooden_hoe",
    "minecraft:stone_sword",
    "minecraft:stone_shovel",
    "minecraft:stone_pickaxe",
    "minecraft:stone_axe",
    "minecraft:stone_hoe",
    "minecraft:golden_sword",
    "minecraft:golden_shovel",
    "minecraft:golden_pickaxe",
    "minecraft:golden_axe",
    "minecraft:golden_hoe",
    "minecraft:iron_sword",
    "minecraft:iron_shovel",
    "minecraft:iron_pickaxe",
    "minecraft:iron_axe",
    "minecraft:iron_hoe",
    "minecraft:diamond_sword",
    "minecraft:diamond_shovel",
    "minecraft:diamond_pickaxe",
    "minecraft:diamond_axe",
    "minecraft:diamond_hoe",
    "minecraft:netherite_sword",
    "minecraft:netherite_shovel",
    "minecraft:netherite_pickaxe",
    "minecraft:netherite_axe",
    "minecraft:netherite_hoe",
    "supplementaries:flute",
    "botania:manasteel_pick",
    "botania:manasteel_shovel",
    "botania:manasteel_axe",
    "botania:manasteel_hoe",
    "botania:manasteel_sword",
    "botania:manasteel_shears",
    "botania:elementium_pickaxe",
    "botania:elementium_shovel",
    "botania:elementium_axe",
    "botania:elementium_hoe",
    "botania:elementium_shears",
    "botania:terra_pick",
    "botania:terra_axe",
    "botania:glass_pickaxe",
  ]);

  // EnderIO Fused Glass
  event.groupItems(
    "kubejs:rei_groups/enderio_fused_glass",
    "EnderIO Fused Glass",
    [/enderio:fused_quartz.*/],
  );

  // EnderIO Clear Glass
  event.groupItems(
    "kubejs:rei_groups/enderio_clear_glass",
    "EnderIO Clear Glass",
    [/enderio:clear_glass.*/],
  );

  // Normal Gateway Pearls
  event.registry.group(
    "kubejs:rei_groups/normal_pearls",
    "Normal Gateway Pearls",
    $VanillaEntryTypes.ITEM,
    (item) =>
      item.value.id === "gateways:gate_pearl" &&
      /^gateways:normal\//.test(item.value.nbt["gateway"] || ""),
  );

  // Titan Gateway Pearls
  event.registry.group(
    "kubejs:rei_groups/titan_pearls",
    "Titan Gateway Pearls",
    $VanillaEntryTypes.ITEM,
    (item) =>
      item.value.id === "gateways:gate_pearl" &&
      /^gateways:titan\//.test(item.value.nbt["gateway"] || ""),
  );

  // Spawn Eggs
  event.groupItems("kubejs:rei_groups/spawn_eggs", "Spawn Eggs", [/spawn_egg/]);
});
