REIEvents.groupEntries((event) => {
  // Categorization by mod
  /** @type {{modName: string; modID: Special.Mod}[]} */
  const mods = [
    { modName: "Additional Lanterns", modID: "additionallanterns" },
    { modName: "Apotheosis", modID: "apotheosis" },
    { modName: "Applied Energistics 2", modID: "ae2" },
    { modName: "Ars Nouveau", modID: "ars_nouveau" },
    { modName: "Bigger Reactors", modID: "biggerreactors" },
    { modName: "Botania", modID: "botania" },
    { modName: "Chipped", modID: "chipped" },
    { modName: "Cluttered", modID: "luphieclutteredmod" },
    { modName: "Coloured Stuff", modID: "colouredstuff" },
    { modName: "Comforts", modID: "comforts" },
    { modName: "Cooking for Blockheads", modID: "cookingforblockheads" },
    { modName: "Crayfish Furniture", modID: "cfm" },
    { modName: "Create Addition", modID: "createaddition" },
    { modName: "Create Sabres", modID: "create_sabers" },
    { modName: "Create Sifter", modID: "createsifter" },
    { modName: "Create Steam 'n Rails", modID: "railways" },
    { modName: "Create", modID: "create" },
    { modName: "Cyclic", modID: "cyclic" },
    { modName: "Draconic Evolution", modID: "draconicevolution" },
    { modName: "Earth Mobs Mod", modID: "earthmobsmod" },
    { modName: "Elevator Mod", modID: "elevatorid" },
    { modName: "EnderIO", modID: "enderio" },
    { modName: "Ex Nihilo Coloratus", modID: "exnihilocoloratus" },
    { modName: "Forcecraft", modID: "forcecraft" },
    { modName: "Friends and Foes", modID: "friendsandfoes" },
    { modName: "Heads", modID: "heads" },
    { modName: "Immersive Engineering", modID: "immersiveengineering" },
    { modName: "Industrial Foregoing", modID: "industrialforegoing" },
    { modName: "Lampcrafting", modID: "lampcrafting" },
    { modName: "Limbs", modID: "limbs" },
    { modName: "Little Logistics", modID: "littlelogistics" },
    { modName: "Macaw Lights", modID: "mcwlights" },
    { modName: "Macaw's Bridges", modID: "mcwbridges" },
    { modName: "Macaw's Doors", modID: "mcwdoors" },
    { modName: "Macaw's Fences", modID: "mcwfences" },
    { modName: "Macaw's Roofs", modID: "mcwroofs" },
    { modName: "Macaw's Windows", modID: "mcwwindows" },
    { modName: "Mining Gadgets", modID: "mininggadgets" },
    { modName: "Mystical Agriculture", modID: "mysticalagriculture" },
    { modName: "Occultism", modID: "occultism" },
    { modName: "Open Stairs", modID: "openstairs" },
    { modName: "Pizzacraft", modID: "pizzacraft" },
    { modName: "RFTools Dimensions", modID: "rftoolsdim" },
    { modName: "Rechiseled Create", modID: "rechiseledcreate" },
    { modName: "Rechiseled", modID: "rechiseled" },
    { modName: "Simple Hats", modID: "simplehats" },
    { modName: "Sophisticated Backpacks", modID: "sophisticatedbackpacks" },
    { modName: "Sophisticated Storage", modID: "sophisticatedstorage" },
    { modName: "Spelled", modID: "spelled" },
    { modName: "Supplementaries", modID: "supplementaries" },
    { modName: "Sushi Go Crafting", modID: "sushigocrafting" },
    { modName: "Thermal", modID: "thermal" },
    { modName: "Tinted Campfires", modID: "tintedcampfires" },
    { modName: "Vinery", modID: "vinery" },
    { modName: "Wormhole", modID: "wormhole" },
    { modName: "X Tones", modID: "xtonesreworked" },
  ];

  mods.forEach((entry) => {
    event.groupItems(
      `kubejs:rei_groups/${entry.modID}`,
      entry.modName,
      `@${entry.modID}`,
    );
  });
});
