# Colourable Stuff config.  For modpack devs: also see the datapack for custom recipes and item tags.
[colouredstuff]

# Items tagged with any 'forge/dyes:' colour including dyes/none will edit blocks in world when used and switch to that colour.  Even when enabled, valid dyes that are also tagged as stationery writing implements will be ignored from this feature, see forge:tools/stationery (for example the Chalk mod items are both dyes and stationery tools)
[colouredstuff.in_world_dye]
# Use dye items on blocks in-world to change dye colour of target block
enabled = true
# Also allows you to sneak and dye multiple blocks from the mod all at once for the same cost (only works if enabled=true also)
multi_block = true
# If enabled, then vanilla blocks can also be dyed in world and converted to the modded block (only works if enabled=true also)
vanilla_override = true
# Will the dye get consumed when dye-ing blocks in world.  Changing to false will mean right clicking blocks with dye will not consume any items from your stack
consume = true

[colouredstuff.water]
# Is the dyed water an infinite source like regular water where new source blocks get generated
infinite = false

[colouredstuff.rgb]
# Add the RGB/rainbow crafting table item.  Setting to false will not register the item
enabled = true
