/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MinecraftPackage {
  /**
   * The name of the modpack
   */
  name: string;
  /**
   * The version of the Minecraft modpack
   */
  version: string;
  /**
   * The version of Minecraft the modpack will use
   */
  minecraftVersion: string;
  /**
   * The version of forge the modpack will use
   */
  forgeVersion: string;
  mods?: MinecraftPackageMods;
  devMods?: MinecraftPackageMods;
}
export interface MinecraftPackageMods {
  /**
   * This interface was referenced by `MinecraftPackageMods`'s JSON-Schema definition
   * via the `patternProperty` ".*".
   */
  [k: string]: {
    id: number;
    version: string;
  };
}
