/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JsonThingsBlockSetType {
  sound_type?: string;
  door_close?: string;
  door_open?: string;
  trapdoor_close?: string;
  trapdoor_open?: string;
  pressure_plate_off?: string;
  pressure_plate_on?: string;
  button_off?: string;
  button_on?: string;
  is_wood?: boolean;
  hanging_sign_sound_type?: string;
  fence_gate_close?: string;
  fence_gate_open?: string;
}
