/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JsonThingsFood {
  /**
   * Defines how much hunger this food restores.
   */
  nutrition: number;
  /**
   * Defines how much saturation this food adds. Saturation is the delay until hunger restarts.
   */
  saturation: number;
  /**
   * Defines if the food is considered meat. Meats are appealing to carnivores like wolves.
   */
  meat?: boolean;
  /**
   * Defines if the food can be eaten fast.
   */
  fast?: boolean;
  /**
   * Defines if the food can be eaten with a full stomach. Should only be used for snack foods and not big meals.
   */
  always_eat?: boolean;
  /**
   * Defines a list of effects that are applied when the food is eaten.
   */
  effects?: {
    effect: string;
    /**
     * Defines how long the effect lasts, in ingame ticks (20ths of a second).
     */
    duration: number;
    /**
     * Defines how strong the effect is. Higher numbers increase the potency of the effect further.
     */
    amplifier?: number;
    /**
     * Defines if the effect should be considered an ambient effect such as coming from a beacon. Ambient effects appear in a different color and without a countdown. It is advised not to set the "ambient" property to true for foods and other contextual effects.
     */
    ambient?: boolean;
    /**
     * Defines if the effect produces particles around the player.
     */
    show_particles?: boolean;
    /**
     * Defines if the effect has an icon in the top right of the HUD.
     */
    show_icon?: boolean;
  }[];
}
