/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JsonThingsItem {
  /**
   * Defines another item to copy properties from.
   */
  parent?: string;
  /**
   * Defines the type of item to construct. Each type has additional properties.
   */
  type?: string;
  /**
   * Defines how much the item stacks. Defaults to 0
   */
  max_stack_size?: number;
  /**
   * Defines how many uses (without Unbreaking) the item has before breaking.
   */
  max_damage?: number;
  /**
   * Defines the item that will be left behind in the crafting table after crafting, or in the furnace when the fuel is spent.
   */
  container?: string;
  /**
   * Defines the item to be edible.
   */
  food?: {
    [k: string]: unknown;
  };
  /**
   * Defines the attribute changes that are applied when this item is equipped.
   */
  attribute_modifiers?: {
    [k: string]: unknown;
  }[];
  /**
   * Defines a color handler for the stack. Color handler provides tint values based on context.
   */
  color_handler?: string;
  /**
   * Defines a list of lines of lore text to show in the tooltip box.
   */
  lore?: (
    | string
    | {
        text?: string;
        italic?: boolean;
        color?: string;
        additionalProperties?: never;
        [k: string]: unknown;
      }
  )[];
  /**
   * Defines a list of tool actions to present to the game. This doesn't make an item able to perform those actions unless it's scripted to do so, without scripting it only declares the item as a kind of tool.
   */
  tool_actions?: string[];
  /**
   * Defines the amount of time this item can burn when used as fuel for a furnace.
   */
  burn_duration?: number;
  /**
   * Defines which creative tab to have the item in.
   */
  group?: string;
  /**
   * Defines which stacks of this item will be added to the creative menu. Each stack can be added to one or more tabs.
   */
  creative_menu_stacks?: {
    tabs: string[];
    nbt?: {
      [k: string]: unknown;
    };
  }[];
}
