import crafttweaker.api.item.IItemStack;
import crafttweaker.api.text.Component;

val color = Globals.colors[ColorName.Magenta];
val textColor = 0xFFFFFF;

val items as IItemStack[] = [
  <item:treasurebags:treasure_bag>.withTag({"silentlib.LootContainer": {LootTable: "treasurebags:bags/magenta", BagType: "treasurebags:magenta"}}),

  // GENERATOR START
  // !THIS SECTION IS MANAGED BY A SCRIPT. DO NOT MANUALLY EDIT THIS SECTION!

  <item:ae2:magenta_paint_ball>,
  <item:ars_nouveau:gilded_sourcestone_alternating>,
  <item:ars_nouveau:gilded_sourcestone_alternating_slab>,
  <item:ars_nouveau:gilded_sourcestone_alternating_stairs>,
  <item:ars_nouveau:gilded_sourcestone_basketweave>,
  <item:ars_nouveau:gilded_sourcestone_basketweave_slab>,
  <item:ars_nouveau:gilded_sourcestone_basketweave_stairs>,
  <item:ars_nouveau:gilded_sourcestone_large_bricks>,
  <item:ars_nouveau:gilded_sourcestone_large_bricks_slab>,
  <item:ars_nouveau:gilded_sourcestone_large_bricks_stairs>,
  <item:ars_nouveau:gilded_sourcestone_mosaic>,
  <item:ars_nouveau:gilded_sourcestone_mosaic_slab>,
  <item:ars_nouveau:gilded_sourcestone_mosaic_stairs>,
  <item:ars_nouveau:gilded_sourcestone_small_bricks>,
  <item:ars_nouveau:gilded_sourcestone_small_bricks_slab>,
  <item:ars_nouveau:gilded_sourcestone_small_bricks_stairs>,
  <item:ars_nouveau:smooth_gilded_sourcestone_alternating>,
  <item:ars_nouveau:smooth_gilded_sourcestone_alternating_slab>,
  <item:ars_nouveau:smooth_gilded_sourcestone_alternating_stairs>,
  <item:ars_nouveau:smooth_gilded_sourcestone_basketweave>,
  <item:ars_nouveau:smooth_gilded_sourcestone_basketweave_slab>,
  <item:ars_nouveau:smooth_gilded_sourcestone_basketweave_stairs>,
  <item:ars_nouveau:smooth_gilded_sourcestone_large_bricks>,
  <item:ars_nouveau:smooth_gilded_sourcestone_large_bricks_slab>,
  <item:ars_nouveau:smooth_gilded_sourcestone_large_bricks_stairs>,
  <item:ars_nouveau:smooth_gilded_sourcestone_mosaic>,
  <item:ars_nouveau:smooth_gilded_sourcestone_mosaic_slab>,
  <item:ars_nouveau:smooth_gilded_sourcestone_mosaic_stairs>,
  <item:ars_nouveau:smooth_gilded_sourcestone_small_bricks>,
  <item:ars_nouveau:smooth_gilded_sourcestone_small_bricks_slab>,
  <item:ars_nouveau:smooth_gilded_sourcestone_small_bricks_stairs>,
  <item:ars_nouveau:smooth_sourcestone>,
  <item:ars_nouveau:smooth_sourcestone_alternating>,
  <item:ars_nouveau:smooth_sourcestone_alternating_slab>,
  <item:ars_nouveau:smooth_sourcestone_alternating_stairs>,
  <item:ars_nouveau:smooth_sourcestone_basketweave>,
  <item:ars_nouveau:smooth_sourcestone_basketweave_stairs>,
  <item:ars_nouveau:smooth_sourcestone_large_bricks>,
  <item:ars_nouveau:smooth_sourcestone_large_bricks_slab>,
  <item:ars_nouveau:smooth_sourcestone_large_bricks_stairs>,
  <item:ars_nouveau:smooth_sourcestone_mosaic>,
  <item:ars_nouveau:smooth_sourcestone_mosaic_slab>,
  <item:ars_nouveau:smooth_sourcestone_mosaic_stairs>,
  <item:ars_nouveau:smooth_sourcestone_slab>,
  <item:ars_nouveau:smooth_sourcestone_small_bricks>,
  <item:ars_nouveau:smooth_sourcestone_small_bricks_slab>,
  <item:ars_nouveau:smooth_sourcestone_small_bricks_stairs>,
  <item:ars_nouveau:smooth_sourcestone_stairs>,
  <item:ars_nouveau:source_berry_pie>,
  <item:ars_nouveau:source_berry_roll>,
  <item:ars_nouveau:source_gem>,
  <item:ars_nouveau:source_gem_block>,
  <item:ars_nouveau:sourceberry_bush>,
  <item:ars_nouveau:sourcestone>,
  <item:ars_nouveau:sourcestone_alternating>,
  <item:ars_nouveau:sourcestone_alternating_slab>,
  <item:ars_nouveau:sourcestone_alternating_stairs>,
  <item:ars_nouveau:sourcestone_basketweave>,
  <item:ars_nouveau:sourcestone_basketweave_slab>,
  <item:ars_nouveau:sourcestone_basketweave_stairs>,
  <item:ars_nouveau:sourcestone_large_bricks>,
  <item:ars_nouveau:sourcestone_large_bricks_slab>,
  <item:ars_nouveau:sourcestone_large_bricks_stairs>,
  <item:ars_nouveau:sourcestone_mosaic>,
  <item:ars_nouveau:sourcestone_mosaic_slab>,
  <item:ars_nouveau:sourcestone_mosaic_stairs>,
  <item:ars_nouveau:sourcestone_slab>,
  <item:ars_nouveau:sourcestone_small_bricks>,
  <item:ars_nouveau:sourcestone_small_bricks_slab>,
  <item:ars_nouveau:sourcestone_small_bricks_stairs>,
  <item:ars_nouveau:sourcestone_stairs>,
  <item:colouredstuff:brick_magenta>,
  <item:colouredstuff:chiseled_sandstone_magenta>,
  <item:colouredstuff:chiseled_stone_bricks_magenta>,
  <item:colouredstuff:cobblestone_magenta>,
  <item:colouredstuff:crafting_table_magenta>,
  <item:colouredstuff:cut_sandstone_magenta>,
  <item:colouredstuff:dirt_magenta>,
  <item:colouredstuff:farmland_magenta>,
  <item:colouredstuff:fence_planks_magenta>,
  <item:colouredstuff:gate_planks_magenta>,
  <item:colouredstuff:leaves_magenta>,
  <item:colouredstuff:log_magenta>,
  <item:colouredstuff:log_stripped_magenta>,
  <item:colouredstuff:path_magenta>,
  <item:colouredstuff:planks_magenta>,
  <item:colouredstuff:sandstone_magenta>,
  <item:colouredstuff:sapling_magenta>,
  <item:colouredstuff:slab_brick_magenta>,
  <item:colouredstuff:slab_cobblestone_magenta>,
  <item:colouredstuff:slab_planks_magenta>,
  <item:colouredstuff:slab_sandstone_magenta>,
  <item:colouredstuff:slab_stone_bricks_magenta>,
  <item:colouredstuff:slab_stone_magenta>,
  <item:colouredstuff:smooth_sandstone_magenta>,
  <item:colouredstuff:stairs_brick_magenta>,
  <item:colouredstuff:stairs_cobblestone_magenta>,
  <item:colouredstuff:stairs_planks_magenta>,
  <item:colouredstuff:stairs_sandstone_magenta>,
  <item:colouredstuff:stairs_stone_bricks_magenta>,
  <item:colouredstuff:stairs_stone_magenta>,
  <item:colouredstuff:stone_bricks_magenta>,
  <item:colouredstuff:stone_magenta>,
  <item:colouredstuff:wall_brick_magenta>,
  <item:colouredstuff:wall_cobblestone_magenta>,
  <item:colouredstuff:wall_planks_magenta>,
  <item:colouredstuff:wall_sandstone_magenta>,
  <item:colouredstuff:wall_stone_bricks_magenta>,
  <item:colouredstuff:wall_stone_magenta>,
  <item:energeticsheep:magenta_energetic_wool>,
  <item:forcecraft:force_brick_magenta>,
  <item:forcecraft:force_brick_magenta_slab>,
  <item:forcecraft:force_brick_magenta_stairs>,
  <item:forcecraft:force_magenta_torch>,
  <item:forcecraft:magenta_force_furnace>,
  <item:minecraft:allium>,
  <item:minecraft:magenta_banner>,
  <item:minecraft:magenta_bed>,
  <item:minecraft:magenta_candle>,
  <item:minecraft:magenta_carpet>,
  <item:minecraft:magenta_concrete>,
  <item:minecraft:magenta_concrete_powder>,
  <item:minecraft:magenta_dye>,
  <item:minecraft:magenta_glazed_terracotta>,
  <item:minecraft:magenta_shulker_box>,
  <item:minecraft:magenta_stained_glass>,
  <item:minecraft:magenta_stained_glass_pane>,
  <item:minecraft:magenta_terracotta>,
  <item:minecraft:magenta_wool>,
  <item:mysticalagriculture:magenta_crop_essence>,
  <item:mysticalagriculture:magenta_crop_seeds>,
  <item:overweight_farming:allium_bush>,
  <item:overweight_farming:overweight_onion_block>,
  <item:overweight_farming:peeled_overweight_onion_block>,
  <item:pizzacraft:onion>,
  <item:pizzacraft:onion_slice>,
  <item:sf5_things:magenta_apple>,
  <item:sf5stuff:composting_bin_magenta>,
  <item:sf5stuff:crucible_magenta>,
  <item:supplementaries:candle_holder_magenta>,
  <item:supplementaries:colouredstuff/sign_post_magenta>,
  <item:supplementaries:flag_magenta>,
  <item:supplementaries:present_magenta>,
  <item:supplementaries:trapped_present_magenta>,
  <item:tinted_torches:magenta_torch>,
  <item:tintedcampfires:magenta_campfire>

  // GENERATOR END
];

for item in items {
  item.addTooltip(Component.literal(color.getName()).withStyle(style => style.withColor(textColor)));

  if (!item.hasTag) {
    <tag:items:skyfactory_5:colored_items>.add(item);
    <tag:items:skyfactory_5:colored_items/magenta>.add(item);
  }
}
